language: node_js

node_js:
  - node

before_script:
  - npm install

script:
  - npm run lint
  - npm run build
  # - npm test

deploy:
  - provider: releases
    file: README.md
    release_notes_file: RELEASE_NOTES.md
    prerelease: true
    overwrite: true
    cleanup: true
    edge: true
    on:
      tags: true
